# goal definition

string question            # the question that the robot will ask to the person (using speech synthetizer)
string success_response    # if the user response string (from speech recog) is different than this one the answer to the question will be taken as a "no"
float64 timeout            # the robot will wait this amount of time for a response from the user

string positive_speech      # the robot will speak this sentence if it has received a ok from the user
string negative_speech     # the robot will speak this sentence if it has received a no from the user
string timeout_speech      # the robot will speak this sentence if no speak was received within timeout
---
# result definition
bool response              # whether the answer to the question is yes or no
bool timeout               # the robot got the response on time
string recognized_speech   # the string that the robot recognized from the user (speech recognition)
---
# feedback
string current_state
string text
